export const clothesTemperature = [
    {
        temperature:28,
    },
    {
        temperature:23,
    },
    {
        temperature:20,
    },
    {
        temperature:17,
    },
    {
        temperature:12,
    },
    {
        temperature:9,
    },
    {
        temperature:5,
    },
    {
        temperature:4,
    },
]

export const clothesRoute = [
    {
        temperature:28,
        clothes:{
            outer:[
                ""
            ],
            top: [
                "url('./images/clothes/28~/top/민소매.png')",
                "url('./images/clothes/28~/top/반팔 셔츠1.png')",
                "url('./images/clothes/28~/top/반팔 셔츠2.png')",
                "url('./images/clothes/28~/top/반팔 셔츠3.png')",
                "url('./images/clothes/28~/top/반팔 티1.png')",
                "url('./images/clothes/28~/top/반팔 티2.png')",
            ],
            pants: [
                "url('./images/clothes/28~/pants/면 바지.png')",
                "url('./images/clothes/28~/pants/반바지1.png')",
                "url('./images/clothes/28~/pants/반바지2.png')",
                "url('./images/clothes/28~/pants/슬랙스1.png')",
                "url('./images/clothes/28~/pants/슬랙스2.png')",
                "url('./images/clothes/28~/pants/청바지.png')",
                "url('./images/clothes/28~/pants/카고 바지.png')",
                "url('./images/clothes/28~/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/28~/socks/socks1.png')",
                "url('./images/clothes/28~/socks/socks2.png')",
                "url('./images/clothes/28~/socks/socks3.png')",
                "url('./images/clothes/28~/socks/socks4.png')",
                "url('./images/clothes/28~/socks/socks5.png')",
                "url('./images/clothes/28~/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/28~/acc/목걸이1.png')",
                "url('./images/clothes/28~/acc/목걸이2.png')",
                "url('./images/clothes/28~/acc/목걸이3.png')",
                "url('./images/clothes/28~/acc/선글라스1.png')",
                "url('./images/clothes/28~/acc/선글라스2.png')",
                "url('./images/clothes/28~/acc/선글라스3.png')",
                "url('./images/clothes/28~/acc/캡 모자.png')",
                "url('./images/clothes/28~/acc/캡 모자2.png')",
                "url('./images/clothes/28~/acc/캡 모자3.png')",
                "url('./images/clothes/28~/acc/팔찌1.png')",
                "url('./images/clothes/28~/acc/팔찌2.png')",
                "url('./images/clothes/28~/acc/팔찌3.png')",
                "url('./images/clothes/28~/acc/팔찌4.png')",
                "url('./images/clothes/28~/acc/팔찌5.png')",
            ],
        },
        clothesName:{
            outer:[
                ""
            ],
            top: [
                "민소매",
                "반팔 셔츠",
                "반팔 셔츠",
                "반팔 셔츠",
                "반팔 티",
                "반팔 티",
            ],
            pants: [
                "면 바지",
                "반바지",
                "반바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "목걸이",
                "목걸이",
                "목걸이",
                "선글라스",
                "선글라스",
                "선글라스",
                "캡 모자",
                "캡 모자",
                "캡 모자",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
            ],
        },
    },
    {
        temperature:23,
        clothes:{
            outer: [
                ""
            ],
            top: [
                "url('./images/clothes/27~23/top/반팔 셔츠1.png')",
                "url('./images/clothes/27~23/top/반팔 셔츠2.png')",
                "url('./images/clothes/27~23/top/반팔 셔츠3.png')",
                "url('./images/clothes/27~23/top/반팔 티1.png')",
                "url('./images/clothes/27~23/top/반팔 티2.png')",
                "url('./images/clothes/27~23/top/셔츠2.png')",
            ],
            pants: [
                "url('./images/clothes/27~23/pants/면 바지.png')",
                "url('./images/clothes/27~23/pants/반바지1.png')",
                "url('./images/clothes/27~23/pants/반바지2.png')",
                "url('./images/clothes/27~23/pants/슬랙스1.png')",
                "url('./images/clothes/27~23/pants/슬랙스2.png')",
                "url('./images/clothes/27~23/pants/청바지.png')",
                "url('./images/clothes/27~23/pants/카고 바지.png')",
                "url('./images/clothes/27~23/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/27~23/socks/socks1.png')",
                "url('./images/clothes/27~23/socks/socks2.png')",
                "url('./images/clothes/27~23/socks/socks3.png')",
                "url('./images/clothes/27~23/socks/socks4.png')",
                "url('./images/clothes/27~23/socks/socks5.png')",
                "url('./images/clothes/27~23/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/27~23/acc/목걸이1.png')",
                "url('./images/clothes/27~23/acc/목걸이2.png')",
                "url('./images/clothes/27~23/acc/목걸이3.png')",
                "url('./images/clothes/27~23/acc/선글라스1.png')",
                "url('./images/clothes/27~23/acc/선글라스2.png')",
                "url('./images/clothes/27~23/acc/선글라스3.png')",
                "url('./images/clothes/27~23/acc/캡 모자.png')",
                "url('./images/clothes/27~23/acc/캡 모자2.png')",
                "url('./images/clothes/27~23/acc/캡 모자3.png')",
                "url('./images/clothes/27~23/acc/팔찌1.png')",
                "url('./images/clothes/27~23/acc/팔찌2.png')",
                "url('./images/clothes/27~23/acc/팔찌3.png')",
                "url('./images/clothes/27~23/acc/팔찌4.png')",
                "url('./images/clothes/27~23/acc/팔찌5.png')",
            ],
        },
        clothesName:{
            outer: [
                ""
            ],
            top: [
                "반팔 셔츠",
                "반팔 셔츠",
                "반팔 셔츠",
                "반팔 티",
                "반팔 티",
                "셔츠2",
            ],
            pants: [
                "면 바지",
                "반바지",
                "반바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "목걸이",
                "목걸이",
                "목걸이",
                "선글라스",
                "선글라스",
                "선글라스",
                "캡 모자",
                "캡 모자",
                "캡 모자",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
            ],
        },
    },
    {
        temperature:20,
        clothes:{
            outer: [
                "url('./images/clothes/22~20/outer/가디건1.png')",
                "url('./images/clothes/22~20/outer/가디건2.png')",
                "url('./images/clothes/22~20/outer/블레이저1.png')",
                "url('./images/clothes/22~20/outer/블레이저2.png')",
                "url('./images/clothes/22~20/outer/트레이닝복1.png')",
                "url('./images/clothes/22~20/outer/트레이닝복2.png')",
                "url('./images/clothes/22~20/outer/후드집업.png')",
            ],
            top: [
                "url('./images/clothes/22~20/top/긴팔 티1.png')",
                "url('./images/clothes/22~20/top/긴팔 티2.png')",
                "url('./images/clothes/22~20/top/긴팔 티3.png')",
                "url('./images/clothes/22~20/top/긴팔 티4.png')",
                "url('./images/clothes/22~20/top/맨투맨.png')",
                "url('./images/clothes/22~20/top/맨투맨2.png')",
                "url('./images/clothes/22~20/top/셔츠.png')",
                "url('./images/clothes/22~20/top/셔츠2.png')",
                "url('./images/clothes/22~20/top/후드티1.png')",
                "url('./images/clothes/22~20/top/후드티2.png')",
                "url('./images/clothes/22~20/top/후드티3.png')",
            ],
            pants: [
                "url('./images/clothes/22~20/pants/면 바지.png')",
                "url('./images/clothes/22~20/pants/슬랙스1.png')",
                "url('./images/clothes/22~20/pants/슬랙스2.png')",
                "url('./images/clothes/22~20/pants/청바지.png')",
                "url('./images/clothes/22~20/pants/카고 바지.png')",
                "url('./images/clothes/22~20/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/22~20/socks/socks1.png')",
                "url('./images/clothes/22~20/socks/socks2.png')",
                "url('./images/clothes/22~20/socks/socks3.png')",
                "url('./images/clothes/22~20/socks/socks4.png')",
                "url('./images/clothes/22~20/socks/socks5.png')",
                "url('./images/clothes/22~20/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/22~20/acc/목걸이1.png')",
                "url('./images/clothes/22~20/acc/목걸이2.png')",
                "url('./images/clothes/22~20/acc/목걸이3.png')",
                "url('./images/clothes/22~20/acc/캡 모자.png')",
                "url('./images/clothes/22~20/acc/캡 모자2.png')",
                "url('./images/clothes/22~20/acc/캡 모자3.png')",
                "url('./images/clothes/22~20/acc/팔찌1.png')",
                "url('./images/clothes/22~20/acc/팔찌2.png')",
                "url('./images/clothes/22~20/acc/팔찌3.png')",
                "url('./images/clothes/22~20/acc/팔찌4.png')",
                "url('./images/clothes/22~20/acc/팔찌5.png')",
            ],
        },
        clothesName:{
            outer: [
                "가디건",
                "가디건",
                "블레이저",
                "블레이저",
                "트레이닝 탑",
                "트레이닝 탑",
                "후드 집업",
            ],
            top: [
                "긴팔 티",
                "긴팔 티",
                "긴팔 티",
                "긴팔 티",
                "맨투맨",
                "맨투맨",
                "셔츠",
                "셔츠",
                "후드티",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "목걸이",
                "목걸이",
                "목걸이",
                "캡 모자",
                "캡 모자",
                "캡 모자",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
            ],
        },
    },
    {
        temperature:17,
        clothes:{
            outer: [
                "url('./images/clothes/19~17/outer/가디건1.png')",
                "url('./images/clothes/19~17/outer/가디건2.png')",
                "url('./images/clothes/19~17/outer/바람막이.png')",
                "url('./images/clothes/19~17/outer/바시티 자켓1.png')",
                "url('./images/clothes/19~17/outer/바시티 자켓2.png')",
                "url('./images/clothes/19~17/outer/블레이저1.png')",
                "url('./images/clothes/19~17/outer/블레이저2.png')",
                "url('./images/clothes/19~17/outer/청자켓.png')",
                "url('./images/clothes/19~17/outer/트레이닝복1.png')",
                "url('./images/clothes/19~17/outer/트레이닝복2.png')",
                "url('./images/clothes/19~17/outer/후드집업.png')",
            ],
            top: [
                "url('./images/clothes/19~17/top/긴팔 티1.png')",
                "url('./images/clothes/19~17/top/긴팔 티2.png')",
                "url('./images/clothes/19~17/top/긴팔 티3.png')",
                "url('./images/clothes/19~17/top/긴팔 티4.png')",
                "url('./images/clothes/19~17/top/맨투맨.png')",
                "url('./images/clothes/19~17/top/맨투맨2.png')",
                "url('./images/clothes/19~17/top/셔츠.png')",
                "url('./images/clothes/19~17/top/후드티1.png')",
                "url('./images/clothes/19~17/top/후드티2.png')",
                "url('./images/clothes/19~17/top/후드티3.png')",
            ],
            pants: [
                "url('./images/clothes/19~17/pants/면 바지.png')",
                "url('./images/clothes/19~17/pants/슬랙스1.png')",
                "url('./images/clothes/19~17/pants/슬랙스2.png')",
                "url('./images/clothes/19~17/pants/청바지.png')",
                "url('./images/clothes/19~17/pants/카고 바지.png')",
                "url('./images/clothes/19~17/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/19~17/socks/socks1.png')",
                "url('./images/clothes/19~17/socks/socks2.png')",
                "url('./images/clothes/19~17/socks/socks3.png')",
                "url('./images/clothes/19~17/socks/socks4.png')",
                "url('./images/clothes/19~17/socks/socks5.png')",
                "url('./images/clothes/19~17/socks/socks6.png')",
            ],
             acc: [
                "url('./images/clothes/19~17/acc/목걸이1.png')",
                "url('./images/clothes/19~17/acc/목걸이2.png')",
                "url('./images/clothes/19~17/acc/목걸이3.png')",
                "url('./images/clothes/19~17/acc/캡 모자.png')",
                "url('./images/clothes/19~17/acc/캡 모자2.png')",
                "url('./images/clothes/19~17/acc/캡 모자3.png')",
                "url('./images/clothes/19~17/acc/팔찌1.png')",
                "url('./images/clothes/19~17/acc/팔찌2.png')",
                "url('./images/clothes/19~17/acc/팔찌3.png')",
                "url('./images/clothes/19~17/acc/팔찌4.png')",
                "url('./images/clothes/19~17/acc/팔찌5.png')",
            ],
        },
        clothesName:{
            outer: [
                "가디건",
                "가디건",
                "바람막이",
                "바시티 자켓",
                "바시티 자켓",
                "블레이저",
                "블레이저",
                "청자켓",
                "트레이닝 탑",
                "트레이닝 탑",
                "후드 집업",
            ],
            top: [
                "긴팔 티",
                "긴팔 티",
                "긴팔 티",
                "긴팔 티",
                "맨투맨",
                "맨투맨",
                "셔츠",
                "후드티",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "목걸이",
                "목걸이",
                "목걸이",
                "캡 모자",
                "캡 모자",
                "캡 모자",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
            ],
        },
    },
    {
        temperature:12,
        clothes:{
            outer: [
                "url('./images/clothes/16~12/outer/가디건1.png')",
                "url('./images/clothes/16~12/outer/가디건2.png')",
                "url('./images/clothes/16~12/outer/바람막이.png')",
                "url('./images/clothes/16~12/outer/바시티 자켓1.png')",
                "url('./images/clothes/16~12/outer/바시티 자켓2.png')",
                "url('./images/clothes/16~12/outer/블레이저1.png')",
                "url('./images/clothes/16~12/outer/블레이저2.png')",
                "url('./images/clothes/16~12/outer/청자켓.png')",
                "url('./images/clothes/16~12/outer/코트1.png')",
                "url('./images/clothes/16~12/outer/코트2.png')",
                "url('./images/clothes/16~12/outer/트레이닝복1.png')",
                "url('./images/clothes/16~12/outer/트레이닝복2.png')",
                "url('./images/clothes/16~12/outer/트렌치 코트.png')",
                "url('./images/clothes/16~12/outer/후드집업.png')",
            ],
            top: [
                "url('./images/clothes/16~12/top/맨투맨.png')",
                "url('./images/clothes/16~12/top/맨투맨2.png')",
                "url('./images/clothes/16~12/top/목폴라.png')",
                "url('./images/clothes/16~12/top/후드티1.png')",
                "url('./images/clothes/16~12/top/후드티2.png')",
            ],
            pants: [
                "url('./images/clothes/16~12/pants/면 바지.png')",
                "url('./images/clothes/16~12/pants/슬랙스1.png')",
                "url('./images/clothes/16~12/pants/슬랙스2.png')",
                "url('./images/clothes/16~12/pants/청바지.png')",
                "url('./images/clothes/16~12/pants/카고 바지.png')",
                "url('./images/clothes/16~12/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/16~12/socks/socks1.png')",
                "url('./images/clothes/16~12/socks/socks2.png')",
                "url('./images/clothes/16~12/socks/socks3.png')",
                "url('./images/clothes/16~12/socks/socks4.png')",
                "url('./images/clothes/16~12/socks/socks5.png')",
                "url('./images/clothes/16~12/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/16~12/acc/목걸이1.png')",
                "url('./images/clothes/16~12/acc/목걸이2.png')",
                "url('./images/clothes/16~12/acc/목걸이3.png')",
                "url('./images/clothes/16~12/acc/캡 모자.png')",
                "url('./images/clothes/16~12/acc/캡 모자2.png')",
                "url('./images/clothes/16~12/acc/캡 모자3.png')",
                "url('./images/clothes/16~12/acc/팔찌1.png')",
                "url('./images/clothes/16~12/acc/팔찌2.png')",
                "url('./images/clothes/16~12/acc/팔찌3.png')",
                "url('./images/clothes/16~12/acc/팔찌4.png')",
                "url('./images/clothes/16~12/acc/팔찌5.png')",
            ],
        },
        clothesName:{
            outer: [
                "가디건",
                "가디건",
                "바람막이",
                "바시티 자켓",
                "바시티 자켓",
                "블레이저",
                "블레이저",
                "청자켓",
                "코트",
                "코트",
                "트레이닝 탑",
                "트레이닝 탑",
                "트렌치 코트",
                "후드 집업",
            ],
            top: [
                "맨투맨",
                "맨투맨",
                "목폴라",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "목걸이",
                "목걸이",
                "목걸이",
                "캡 모자",
                "캡 모자",
                "캡 모자",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
            ],
        },
    },
    {
        temperature:9,
        clothes:{
            outer: [
                "url('./images/clothes/11~9/outer/가죽자켓.png')",
                "url('./images/clothes/11~9/outer/경량 패딩.png')",
                "url('./images/clothes/11~9/outer/경량 패딩2.png')",
                "url('./images/clothes/11~9/outer/코트1.png')",
                "url('./images/clothes/11~9/outer/코트2.png')",
                "url('./images/clothes/11~9/outer/트렌치 코트.png')",
                "url('./images/clothes/11~9/outer/후리스.png')",
            ],
            top: [
                "url('./images/clothes/11~9/top/니트.png')",
                "url('./images/clothes/11~9/top/니트2.png')",
                "url('./images/clothes/11~9/top/니트3.png')",
                "url('./images/clothes/11~9/top/맨투맨.png')",
                "url('./images/clothes/11~9/top/목폴라.png')",
                "url('./images/clothes/11~9/top/후드티1.png')",
                "url('./images/clothes/11~9/top/후드티2.png')",
            ],
            pants: [
                "url('./images/clothes/11~9/pants/면 바지.png')",
                "url('./images/clothes/11~9/pants/슬랙스1.png')",
                "url('./images/clothes/11~9/pants/슬랙스2.png')",
                "url('./images/clothes/11~9/pants/청바지.png')",
                "url('./images/clothes/11~9/pants/카고 바지.png')",
                "url('./images/clothes/11~9/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/11~9/socks/socks1.png')",
                "url('./images/clothes/11~9/socks/socks2.png')",
                "url('./images/clothes/11~9/socks/socks3.png')",
                "url('./images/clothes/11~9/socks/socks4.png')",
                "url('./images/clothes/11~9/socks/socks5.png')",
                "url('./images/clothes/11~9/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/11~9/acc/귀도리.png')",
                "url('./images/clothes/11~9/acc/목도리.png')",
                "url('./images/clothes/11~9/acc/목도리2.png')",
                "url('./images/clothes/11~9/acc/비니.png')",
                "url('./images/clothes/11~9/acc/비니2.png')",
                "url('./images/clothes/11~9/acc/장갑.png')",
                "url('./images/clothes/11~9/acc/장갑2.png')",
                "url('./images/clothes/11~9/acc/캡 모자.png')",
                "url('./images/clothes/11~9/acc/캡 모자2.png')",
                "url('./images/clothes/11~9/acc/캡 모자3.png')",
            ]
        },
        clothesName:{
            outer: [
                "가죽 자켓",
                "경량 패딩",
                "경량 패딩",
                "코트",
                "코트",
                "트렌치 코트",
                "후리스",
            ],
            top: [
                "니트",
                "니트",
                "니트",
                "맨투맨",
                "목폴라",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "귀도리",
                "목도리",
                "목도리",
                "비니",
                "비니",
                "장갑",
                "장갑",
                "캡 모자",
                "캡 모자",
                "캡 모자",
            ],
        },
    },
    {
        temperature:5,
        clothes:{
            outer: [
                "url('./images/clothes/8~5/outer/두꺼운 코트1.png')",
                "url('./images/clothes/8~5/outer/두꺼운 코트2.png')",
                "url('./images/clothes/8~5/outer/무스탕.png')",
                "url('./images/clothes/8~5/outer/숏패딩1.png')",
                "url('./images/clothes/8~5/outer/숏패딩2.png')",
                "url('./images/clothes/8~5/outer/후리스.png')",
            ],
            top: [
                "url('./images/clothes/8~5/top/니트.png')",
                "url('./images/clothes/8~5/top/니트2.png')",
                "url('./images/clothes/8~5/top/니트3.png')",
                "url('./images/clothes/8~5/top/맨투맨.png')",
                "url('./images/clothes/8~5/top/목폴라.png')",
                "url('./images/clothes/8~5/top/후드티1.png')",
                "url('./images/clothes/8~5/top/후드티2.png')",
            ],
            pants: [
                "url('./images/clothes/8~5/pants/면 바지.png')",
                "url('./images/clothes/8~5/pants/슬랙스1.png')",
                "url('./images/clothes/8~5/pants/슬랙스2.png')",
                "url('./images/clothes/8~5/pants/청바지.png')",
                "url('./images/clothes/8~5/pants/카고 바지.png')",
                "url('./images/clothes/8~5/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/8~5/socks/socks1.png')",
                "url('./images/clothes/8~5/socks/socks2.png')",
                "url('./images/clothes/8~5/socks/socks3.png')",
                "url('./images/clothes/8~5/socks/socks4.png')",
                "url('./images/clothes/8~5/socks/socks5.png')",
                "url('./images/clothes/8~5/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/8~5/acc/귀도리.png')",
                "url('./images/clothes/8~5/acc/목도리.png')",
                "url('./images/clothes/8~5/acc/목도리2.png')",
                "url('./images/clothes/8~5/acc/비니.png')",
                "url('./images/clothes/8~5/acc/비니2.png')",
                "url('./images/clothes/8~5/acc/장갑.png')",
                "url('./images/clothes/8~5/acc/장갑2.png')",
                "url('./images/clothes/8~5/acc/캡 모자.png')",
                "url('./images/clothes/8~5/acc/캡 모자2.png')",
                "url('./images/clothes/8~5/acc/캡 모자3.png')",
            ]
        },
        clothesName:{
            outer: [
                "두꺼운 코트",
                "두꺼운 코트",
                "무스탕",
                "숏패딩",
                "숏패딩",
                "후리스",
            ],
            top: [
                "니트",
                "니트",
                "니트",
                "맨투맨",
                "목폴라",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "귀도리",
                "목도리",
                "목도리",
                "비니",
                "비니",
                "장갑",
                "장갑",
                "캡 모자",
                "캡 모자",
                "캡 모자",
            ],
        },
    },
    {
        temperature:4,
        clothes:{
            outer: [
                "url('./images/clothes/~4/outer/두꺼운 코트1.png')",
                "url('./images/clothes/~4/outer/두꺼운 코트2.png')",
                "url('./images/clothes/~4/outer/롱패딩.png')",
                "url('./images/clothes/~4/outer/무스탕.png')",
                "url('./images/clothes/~4/outer/숏패딩1.png')",
                "url('./images/clothes/~4/outer/숏패딩2.png')",
                "url('./images/clothes/~4/outer/헤비 아우터.png')",
            ],
            top: [
                "url('./images/clothes/~4/top/니트.png')",
                "url('./images/clothes/~4/top/니트2.png')",
                "url('./images/clothes/~4/top/니트3.png')",
                "url('./images/clothes/~4/top/맨투맨.png')",
                "url('./images/clothes/~4/top/목폴라.png')",
                "url('./images/clothes/~4/top/후드티1.png')",
                "url('./images/clothes/~4/top/후드티2.png')",
            ],
            pants: [
                "url('./images/clothes/~4/pants/면 바지.png')",
                "url('./images/clothes/~4/pants/슬랙스1.png')",
                "url('./images/clothes/~4/pants/슬랙스2.png')",
                "url('./images/clothes/~4/pants/청바지.png')",
                "url('./images/clothes/~4/pants/카고 바지.png')",
                "url('./images/clothes/~4/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/~4/socks/socks1.png')",
                "url('./images/clothes/~4/socks/socks2.png')",
                "url('./images/clothes/~4/socks/socks3.png')",
                "url('./images/clothes/~4/socks/socks4.png')",
                "url('./images/clothes/~4/socks/socks5.png')",
                "url('./images/clothes/~4/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/~4/acc/귀도리.png')",
                "url('./images/clothes/~4/acc/목도리.png')",
                "url('./images/clothes/~4/acc/목도리2.png')",
                "url('./images/clothes/~4/acc/비니.png')",
                "url('./images/clothes/~4/acc/비니2.png')",
                "url('./images/clothes/~4/acc/장갑.png')",
                "url('./images/clothes/~4/acc/장갑2.png')",
                "url('./images/clothes/~4/acc/캡 모자.png')",
                "url('./images/clothes/~4/acc/캡 모자2.png')",
                "url('./images/clothes/~4/acc/캡 모자3.png')",
            ]
        },
        clothesName:{
            outer: [
                "두꺼운 코트",
                "두꺼운 코트",
                "롱패딩",
                "무스탕",
                "숏패딩",
                "숏패딩",
                "헤비 아우터",
            ],
            top: [
                "니트",
                "니트",
                "니트",
                "맨투맨",
                "목폴라",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "귀도리",
                "목도리",
                "목도리",
                "비니",
                "비니",
                "장갑",
                "장갑",
                "캡 모자",
                "캡 모자",
                "캡 모자",
            ],
        },
    },
];

// export const byTemperatureTip = [
//     {
//         temperature:28,
//         ment: [
//             "🌡️ 28˚ 이상",
//             `"꼭.. 나가야 하는거지..?"`,
//             "따뜻하기보다는 더운 날씨, 가급적 바깥 활동은 피해주세요!",
//             "추천: 민소매, 반팔 티, 반바지, 린넨 옷",
//         ],
//     },
//     {
//         temperature:23,
//         ment: [
//             "🌡️ 27˚ ~ 23˚",
//             `"바깥에 오래 있을 생각은 아니지?"`,
//             "무더위는 아니지만 더운 날씨",
//             "추천: 반팔, 얇은 셔츠, 반바지, 면바지",
//         ],
//     },
//     {
//         temperature:20,
//         ment: [
//             "🌡️ 22˚ ~ 20˚",
//             `"따뜻한 봄, 초가을 정도의 날씨"`,
//             "가볍게 입고 벗을 수 있는 외투 챙기는거 어떠세요?",
//             "추천: 가디건, 후드집업, 블레이저, 얇은 긴팔, 청바지",
//         ],
//     },
//     {
//         temperature:17,
//         ment: [
//             "🌡️ 19˚ ~ 17˚",
//             `"약간은 서늘한듯, 활동하기 딱 좋은 기온"`,
//             "산책하기 딱 좋은 날씨",
//             "추천: 바시티 자켓, 청자켓, 바람막이, 후드티, 니트",
//         ],
//     },
//     {
//         temperature:12,
//         ment: [
//             "🌡️ 16˚ ~ 12˚",
//             `"트렌치 코트, 타이밍인거 알지?"`,
//             "슬슬 추위를 느끼게 되는 기온, 감기 조심!",
//             "추천: 트렌치 코트, 간절기 자켓, 따뜻한 니트",
//         ],
//     },
//     {
//         temperature:9,
//         ment: [
//             "🌡️ 11˚ ~ 9˚",
//             `"슬슬 보온을 챙겨야하는 기온"`,
//             "두꺼운 점퍼는 약간 덥게 느껴질 수 있지만, 어느정도 쌀쌀한",
//             "추천: 코트, 후리스, 가죽 자켓, 경량 패딩",
//         ],
//     },
//     {
//         temperature:5,
//         ment: [
//             "🌡️ 8˚ ~ 5˚",
//             `"겨울의 시작과 끝의 온도"`,
//             "장롱 속 패딩을 꺼내기 좋은 지금!",
//             "추천: 두꺼운 코트, 숏패딩, 무스탕",
//         ],
//     },
//     {
//         temperature:4,
//         ment: [
//             "🌡️ 4˚ 이하",
//             `"패딩은 곧 나의 피부"`,
//             "비니, 목도리, 장갑끼는거 어때요?",
//             "추천: 헤비 아우터, 롱패딩, 누빔 옷, 히트 택"
//         ],
//     },
// ];