export const clothesTemperature = [
    {
        temperature:28,
    },
    {
        temperature:23,
    },
    {
        temperature:20,
    },
    {
        temperature:17,
    },
    {
        temperature:12,
    },
    {
        temperature:9,
    },
    {
        temperature:5,
    },
    {
        temperature:4,
    },
]

export const clothesRoute = [
    {
        temperature:28,
        clothes:{
            outer:[
                ""
            ],
            top: [
                "url('./images/clothes/28~/top/민소매.png')",
                "url('./images/clothes/28~/top/반팔 셔츠1.png')",
                "url('./images/clothes/28~/top/반팔 셔츠2.png')",
                "url('./images/clothes/28~/top/반팔 셔츠3.png')",
                "url('./images/clothes/28~/top/반팔 티1.png')",
                "url('./images/clothes/28~/top/반팔 티2.png')",
            ],
            pants: [
                "url('./images/clothes/28~/pants/면 바지.png')",
                "url('./images/clothes/28~/pants/반바지1.png')",
                "url('./images/clothes/28~/pants/반바지2.png')",
                "url('./images/clothes/28~/pants/슬랙스1.png')",
                "url('./images/clothes/28~/pants/슬랙스2.png')",
                "url('./images/clothes/28~/pants/청바지.png')",
                "url('./images/clothes/28~/pants/카고 바지.png')",
                "url('./images/clothes/28~/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/28~/socks/socks1.png')",
                "url('./images/clothes/28~/socks/socks2.png')",
                "url('./images/clothes/28~/socks/socks3.png')",
                "url('./images/clothes/28~/socks/socks4.png')",
                "url('./images/clothes/28~/socks/socks5.png')",
                "url('./images/clothes/28~/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/28~/acc/목걸이1.png')",
                "url('./images/clothes/28~/acc/목걸이2.png')",
                "url('./images/clothes/28~/acc/목걸이3.png')",
                "url('./images/clothes/28~/acc/선글라스1.png')",
                "url('./images/clothes/28~/acc/선글라스2.png')",
                "url('./images/clothes/28~/acc/선글라스3.png')",
                "url('./images/clothes/28~/acc/캡 모자.png')",
                "url('./images/clothes/28~/acc/캡 모자2.png')",
                "url('./images/clothes/28~/acc/캡 모자3.png')",
                "url('./images/clothes/28~/acc/팔찌1.png')",
                "url('./images/clothes/28~/acc/팔찌2.png')",
                "url('./images/clothes/28~/acc/팔찌3.png')",
                "url('./images/clothes/28~/acc/팔찌4.png')",
                "url('./images/clothes/28~/acc/팔찌5.png')",
            ],
        },
        clothesName:{
            outer:[
                ""
            ],
            top: [
                "민소매",
                "반팔 셔츠",
                "반팔 셔츠",
                "반팔 셔츠",
                "반팔 티",
                "반팔 티",
            ],
            pants: [
                "면 바지",
                "반바지",
                "반바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "목걸이",
                "목걸이",
                "목걸이",
                "선글라스",
                "선글라스",
                "선글라스",
                "캡 모자",
                "캡 모자",
                "캡 모자",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
            ],
        },
    },
    {
        temperature:23,
        clothes:{
            outer: [
                ""
            ],
            top: [
                "url('./images/clothes/27~23/top/반팔 셔츠1.png')",
                "url('./images/clothes/27~23/top/반팔 셔츠2.png')",
                "url('./images/clothes/27~23/top/반팔 셔츠3.png')",
                "url('./images/clothes/27~23/top/반팔 티1.png')",
                "url('./images/clothes/27~23/top/반팔 티2.png')",
                "url('./images/clothes/27~23/top/셔츠2.png')",
            ],
            pants: [
                "url('./images/clothes/27~23/pants/면 바지.png')",
                "url('./images/clothes/27~23/pants/반바지1.png')",
                "url('./images/clothes/27~23/pants/반바지2.png')",
                "url('./images/clothes/27~23/pants/슬랙스1.png')",
                "url('./images/clothes/27~23/pants/슬랙스2.png')",
                "url('./images/clothes/27~23/pants/청바지.png')",
                "url('./images/clothes/27~23/pants/카고 바지.png')",
                "url('./images/clothes/27~23/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/27~23/socks/socks1.png')",
                "url('./images/clothes/27~23/socks/socks2.png')",
                "url('./images/clothes/27~23/socks/socks3.png')",
                "url('./images/clothes/27~23/socks/socks4.png')",
                "url('./images/clothes/27~23/socks/socks5.png')",
                "url('./images/clothes/27~23/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/27~23/acc/목걸이1.png')",
                "url('./images/clothes/27~23/acc/목걸이2.png')",
                "url('./images/clothes/27~23/acc/목걸이3.png')",
                "url('./images/clothes/27~23/acc/선글라스1.png')",
                "url('./images/clothes/27~23/acc/선글라스2.png')",
                "url('./images/clothes/27~23/acc/선글라스3.png')",
                "url('./images/clothes/27~23/acc/캡 모자.png')",
                "url('./images/clothes/27~23/acc/캡 모자2.png')",
                "url('./images/clothes/27~23/acc/캡 모자3.png')",
                "url('./images/clothes/27~23/acc/팔찌1.png')",
                "url('./images/clothes/27~23/acc/팔찌2.png')",
                "url('./images/clothes/27~23/acc/팔찌3.png')",
                "url('./images/clothes/27~23/acc/팔찌4.png')",
                "url('./images/clothes/27~23/acc/팔찌5.png')",
            ],
        },
        clothesName:{
            outer: [
                ""
            ],
            top: [
                "반팔 셔츠",
                "반팔 셔츠",
                "반팔 셔츠",
                "반팔 티",
                "반팔 티",
                "셔츠2",
            ],
            pants: [
                "면 바지",
                "반바지",
                "반바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "목걸이",
                "목걸이",
                "목걸이",
                "선글라스",
                "선글라스",
                "선글라스",
                "캡 모자",
                "캡 모자",
                "캡 모자",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
            ],
        },
    },
    {
        temperature:20,
        clothes:{
            outer: [
                "url('./images/clothes/22~20/outer/가디건1.png')",
                "url('./images/clothes/22~20/outer/가디건2.png')",
                "url('./images/clothes/22~20/outer/블레이저1.png')",
                "url('./images/clothes/22~20/outer/블레이저2.png')",
                "url('./images/clothes/22~20/outer/트레이닝복1.png')",
                "url('./images/clothes/22~20/outer/트레이닝복2.png')",
                "url('./images/clothes/22~20/outer/후드집업.png')",
            ],
            top: [
                "url('./images/clothes/22~20/top/긴팔 티1.png')",
                "url('./images/clothes/22~20/top/긴팔 티2.png')",
                "url('./images/clothes/22~20/top/긴팔 티3.png')",
                "url('./images/clothes/22~20/top/긴팔 티4.png')",
                "url('./images/clothes/22~20/top/맨투맨.png')",
                "url('./images/clothes/22~20/top/맨투맨2.png')",
                "url('./images/clothes/22~20/top/셔츠.png')",
                "url('./images/clothes/22~20/top/셔츠2.png')",
                "url('./images/clothes/22~20/top/후드티1.png')",
                "url('./images/clothes/22~20/top/후드티2.png')",
                "url('./images/clothes/22~20/top/후드티3.png')",
            ],
            pants: [
                "url('./images/clothes/22~20/pants/면 바지.png')",
                "url('./images/clothes/22~20/pants/슬랙스1.png')",
                "url('./images/clothes/22~20/pants/슬랙스2.png')",
                "url('./images/clothes/22~20/pants/청바지.png')",
                "url('./images/clothes/22~20/pants/카고 바지.png')",
                "url('./images/clothes/22~20/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/22~20/socks/socks1.png')",
                "url('./images/clothes/22~20/socks/socks2.png')",
                "url('./images/clothes/22~20/socks/socks3.png')",
                "url('./images/clothes/22~20/socks/socks4.png')",
                "url('./images/clothes/22~20/socks/socks5.png')",
                "url('./images/clothes/22~20/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/22~20/acc/목걸이1.png')",
                "url('./images/clothes/22~20/acc/목걸이2.png')",
                "url('./images/clothes/22~20/acc/목걸이3.png')",
                "url('./images/clothes/22~20/acc/캡 모자.png')",
                "url('./images/clothes/22~20/acc/캡 모자2.png')",
                "url('./images/clothes/22~20/acc/캡 모자3.png')",
                "url('./images/clothes/22~20/acc/팔찌1.png')",
                "url('./images/clothes/22~20/acc/팔찌2.png')",
                "url('./images/clothes/22~20/acc/팔찌3.png')",
                "url('./images/clothes/22~20/acc/팔찌4.png')",
                "url('./images/clothes/22~20/acc/팔찌5.png')",
            ],
        },
        clothesName:{
            outer: [
                "가디건",
                "가디건",
                "블레이저",
                "블레이저",
                "트레이닝 탑",
                "트레이닝 탑",
                "후드 집업",
            ],
            top: [
                "긴팔 티",
                "긴팔 티",
                "긴팔 티",
                "긴팔 티",
                "맨투맨",
                "맨투맨",
                "셔츠",
                "셔츠",
                "후드티",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "목걸이",
                "목걸이",
                "목걸이",
                "캡 모자",
                "캡 모자",
                "캡 모자",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
            ],
        },
    },
    {
        temperature:17,
        clothes:{
            outer: [
                "url('./images/clothes/19~17/outer/가디건1.png')",
                "url('./images/clothes/19~17/outer/가디건2.png')",
                "url('./images/clothes/19~17/outer/바람막이.png')",
                "url('./images/clothes/19~17/outer/바시티 자켓1.png')",
                "url('./images/clothes/19~17/outer/바시티 자켓2.png')",
                "url('./images/clothes/19~17/outer/블레이저1.png')",
                "url('./images/clothes/19~17/outer/블레이저2.png')",
                "url('./images/clothes/19~17/outer/청자켓.png')",
                "url('./images/clothes/19~17/outer/트레이닝복1.png')",
                "url('./images/clothes/19~17/outer/트레이닝복2.png')",
                "url('./images/clothes/19~17/outer/후드집업.png')",
            ],
            top: [
                "url('./images/clothes/19~17/top/긴팔 티1.png')",
                "url('./images/clothes/19~17/top/긴팔 티2.png')",
                "url('./images/clothes/19~17/top/긴팔 티3.png')",
                "url('./images/clothes/19~17/top/긴팔 티4.png')",
                "url('./images/clothes/19~17/top/맨투맨.png')",
                "url('./images/clothes/19~17/top/맨투맨2.png')",
                "url('./images/clothes/19~17/top/셔츠.png')",
                "url('./images/clothes/19~17/top/후드티1.png')",
                "url('./images/clothes/19~17/top/후드티2.png')",
                "url('./images/clothes/19~17/top/후드티3.png')",
            ],
            pants: [
                "url('./images/clothes/19~17/pants/면 바지.png')",
                "url('./images/clothes/19~17/pants/슬랙스1.png')",
                "url('./images/clothes/19~17/pants/슬랙스2.png')",
                "url('./images/clothes/19~17/pants/청바지.png')",
                "url('./images/clothes/19~17/pants/카고 바지.png')",
                "url('./images/clothes/19~17/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/19~17/socks/socks1.png')",
                "url('./images/clothes/19~17/socks/socks2.png')",
                "url('./images/clothes/19~17/socks/socks3.png')",
                "url('./images/clothes/19~17/socks/socks4.png')",
                "url('./images/clothes/19~17/socks/socks5.png')",
                "url('./images/clothes/19~17/socks/socks6.png')",
            ],
             acc: [
                "url('./images/clothes/19~17/acc/목걸이1.png')",
                "url('./images/clothes/19~17/acc/목걸이2.png')",
                "url('./images/clothes/19~17/acc/목걸이3.png')",
                "url('./images/clothes/19~17/acc/캡 모자.png')",
                "url('./images/clothes/19~17/acc/캡 모자2.png')",
                "url('./images/clothes/19~17/acc/캡 모자3.png')",
                "url('./images/clothes/19~17/acc/팔찌1.png')",
                "url('./images/clothes/19~17/acc/팔찌2.png')",
                "url('./images/clothes/19~17/acc/팔찌3.png')",
                "url('./images/clothes/19~17/acc/팔찌4.png')",
                "url('./images/clothes/19~17/acc/팔찌5.png')",
            ],
        },
        clothesName:{
            outer: [
                "가디건",
                "가디건",
                "바람막이",
                "바시티 자켓",
                "바시티 자켓",
                "블레이저",
                "블레이저",
                "청자켓",
                "트레이닝 탑",
                "트레이닝 탑",
                "후드 집업",
            ],
            top: [
                "긴팔 티",
                "긴팔 티",
                "긴팔 티",
                "긴팔 티",
                "맨투맨",
                "맨투맨",
                "셔츠",
                "후드티",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "목걸이",
                "목걸이",
                "목걸이",
                "캡 모자",
                "캡 모자",
                "캡 모자",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
            ],
        },
    },
    {
        temperature:12,
        clothes:{
            outer: [
                "url('./images/clothes/16~12/outer/가디건1.png')",
                "url('./images/clothes/16~12/outer/가디건2.png')",
                "url('./images/clothes/16~12/outer/바람막이.png')",
                "url('./images/clothes/16~12/outer/바시티 자켓1.png')",
                "url('./images/clothes/16~12/outer/바시티 자켓2.png')",
                "url('./images/clothes/16~12/outer/블레이저1.png')",
                "url('./images/clothes/16~12/outer/블레이저2.png')",
                "url('./images/clothes/16~12/outer/청자켓.png')",
                "url('./images/clothes/16~12/outer/코트1.png')",
                "url('./images/clothes/16~12/outer/코트2.png')",
                "url('./images/clothes/16~12/outer/트레이닝복1.png')",
                "url('./images/clothes/16~12/outer/트레이닝복2.png')",
                "url('./images/clothes/16~12/outer/트렌치 코트.png')",
                "url('./images/clothes/16~12/outer/후드집업.png')",
            ],
            top: [
                "url('./images/clothes/16~12/top/맨투맨.png')",
                "url('./images/clothes/16~12/top/맨투맨2.png')",
                "url('./images/clothes/16~12/top/목폴라.png')",
                "url('./images/clothes/16~12/top/후드티1.png')",
                "url('./images/clothes/16~12/top/후드티2.png')",
            ],
            pants: [
                "url('./images/clothes/16~12/pants/면 바지.png')",
                "url('./images/clothes/16~12/pants/슬랙스1.png')",
                "url('./images/clothes/16~12/pants/슬랙스2.png')",
                "url('./images/clothes/16~12/pants/청바지.png')",
                "url('./images/clothes/16~12/pants/카고 바지.png')",
                "url('./images/clothes/16~12/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/16~12/socks/socks1.png')",
                "url('./images/clothes/16~12/socks/socks2.png')",
                "url('./images/clothes/16~12/socks/socks3.png')",
                "url('./images/clothes/16~12/socks/socks4.png')",
                "url('./images/clothes/16~12/socks/socks5.png')",
                "url('./images/clothes/16~12/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/16~12/acc/목걸이1.png')",
                "url('./images/clothes/16~12/acc/목걸이2.png')",
                "url('./images/clothes/16~12/acc/목걸이3.png')",
                "url('./images/clothes/16~12/acc/캡 모자.png')",
                "url('./images/clothes/16~12/acc/캡 모자2.png')",
                "url('./images/clothes/16~12/acc/캡 모자3.png')",
                "url('./images/clothes/16~12/acc/팔찌1.png')",
                "url('./images/clothes/16~12/acc/팔찌2.png')",
                "url('./images/clothes/16~12/acc/팔찌3.png')",
                "url('./images/clothes/16~12/acc/팔찌4.png')",
                "url('./images/clothes/16~12/acc/팔찌5.png')",
            ],
        },
        clothesName:{
            outer: [
                "가디건",
                "가디건",
                "바람막이",
                "바시티 자켓",
                "바시티 자켓",
                "블레이저",
                "블레이저",
                "청자켓",
                "코트",
                "코트",
                "트레이닝 탑",
                "트레이닝 탑",
                "트렌치 코트",
                "후드 집업",
            ],
            top: [
                "맨투맨",
                "맨투맨",
                "목폴라",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "목걸이",
                "목걸이",
                "목걸이",
                "캡 모자",
                "캡 모자",
                "캡 모자",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
                "팔찌",
            ],
        },
    },
    {
        temperature:9,
        clothes:{
            outer: [
                "url('./images/clothes/11~9/outer/가죽자켓.png')",
                "url('./images/clothes/11~9/outer/경량 패딩.png')",
                "url('./images/clothes/11~9/outer/경량 패딩2.png')",
                "url('./images/clothes/11~9/outer/코트1.png')",
                "url('./images/clothes/11~9/outer/코트2.png')",
                "url('./images/clothes/11~9/outer/트렌치 코트.png')",
                "url('./images/clothes/11~9/outer/후리스.png')",
            ],
            top: [
                "url('./images/clothes/11~9/top/니트.png')",
                "url('./images/clothes/11~9/top/니트2.png')",
                "url('./images/clothes/11~9/top/니트3.png')",
                "url('./images/clothes/11~9/top/맨투맨.png')",
                "url('./images/clothes/11~9/top/목폴라.png')",
                "url('./images/clothes/11~9/top/후드티1.png')",
                "url('./images/clothes/11~9/top/후드티2.png')",
            ],
            pants: [
                "url('./images/clothes/11~9/pants/면 바지.png')",
                "url('./images/clothes/11~9/pants/슬랙스1.png')",
                "url('./images/clothes/11~9/pants/슬랙스2.png')",
                "url('./images/clothes/11~9/pants/청바지.png')",
                "url('./images/clothes/11~9/pants/카고 바지.png')",
                "url('./images/clothes/11~9/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/11~9/socks/socks1.png')",
                "url('./images/clothes/11~9/socks/socks2.png')",
                "url('./images/clothes/11~9/socks/socks3.png')",
                "url('./images/clothes/11~9/socks/socks4.png')",
                "url('./images/clothes/11~9/socks/socks5.png')",
                "url('./images/clothes/11~9/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/11~9/acc/귀도리.png')",
                "url('./images/clothes/11~9/acc/목도리.png')",
                "url('./images/clothes/11~9/acc/목도리2.png')",
                "url('./images/clothes/11~9/acc/비니.png')",
                "url('./images/clothes/11~9/acc/비니2.png')",
                "url('./images/clothes/11~9/acc/장갑.png')",
                "url('./images/clothes/11~9/acc/장갑2.png')",
                "url('./images/clothes/11~9/acc/캡 모자.png')",
                "url('./images/clothes/11~9/acc/캡 모자2.png')",
                "url('./images/clothes/11~9/acc/캡 모자3.png')",
            ]
        },
        clothesName:{
            outer: [
                "가죽 자켓",
                "경량 패딩",
                "경량 패딩",
                "코트",
                "코트",
                "트렌치 코트",
                "후리스",
            ],
            top: [
                "니트",
                "니트",
                "니트",
                "맨투맨",
                "목폴라",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "귀도리",
                "목도리",
                "목도리",
                "비니",
                "비니",
                "장갑",
                "장갑",
                "캡 모자",
                "캡 모자",
                "캡 모자",
            ],
        },
    },
    {
        temperature:5,
        clothes:{
            outer: [
                "url('./images/clothes/8~5/outer/두꺼운 코트1.png')",
                "url('./images/clothes/8~5/outer/두꺼운 코트2.png')",
                "url('./images/clothes/8~5/outer/무스탕.png')",
                "url('./images/clothes/8~5/outer/숏패딩1.png')",
                "url('./images/clothes/8~5/outer/숏패딩2.png')",
                "url('./images/clothes/8~5/outer/후리스.png')",
            ],
            top: [
                "url('./images/clothes/8~5/top/니트.png')",
                "url('./images/clothes/8~5/top/니트2.png')",
                "url('./images/clothes/8~5/top/니트3.png')",
                "url('./images/clothes/8~5/top/맨투맨.png')",
                "url('./images/clothes/8~5/top/목폴라.png')",
                "url('./images/clothes/8~5/top/후드티1.png')",
                "url('./images/clothes/8~5/top/후드티2.png')",
            ],
            pants: [
                "url('./images/clothes/8~5/pants/면 바지.png')",
                "url('./images/clothes/8~5/pants/슬랙스1.png')",
                "url('./images/clothes/8~5/pants/슬랙스2.png')",
                "url('./images/clothes/8~5/pants/청바지.png')",
                "url('./images/clothes/8~5/pants/카고 바지.png')",
                "url('./images/clothes/8~5/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/8~5/socks/socks1.png')",
                "url('./images/clothes/8~5/socks/socks2.png')",
                "url('./images/clothes/8~5/socks/socks3.png')",
                "url('./images/clothes/8~5/socks/socks4.png')",
                "url('./images/clothes/8~5/socks/socks5.png')",
                "url('./images/clothes/8~5/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/8~5/acc/귀도리.png')",
                "url('./images/clothes/8~5/acc/목도리.png')",
                "url('./images/clothes/8~5/acc/목도리2.png')",
                "url('./images/clothes/8~5/acc/비니.png')",
                "url('./images/clothes/8~5/acc/비니2.png')",
                "url('./images/clothes/8~5/acc/장갑.png')",
                "url('./images/clothes/8~5/acc/장갑2.png')",
                "url('./images/clothes/8~5/acc/캡 모자.png')",
                "url('./images/clothes/8~5/acc/캡 모자2.png')",
                "url('./images/clothes/8~5/acc/캡 모자3.png')",
            ]
        },
        clothesName:{
            outer: [
                "두꺼운 코트",
                "두꺼운 코트",
                "무스탕",
                "숏패딩",
                "숏패딩",
                "후리스",
            ],
            top: [
                "니트",
                "니트",
                "니트",
                "맨투맨",
                "목폴라",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "귀도리",
                "목도리",
                "목도리",
                "비니",
                "비니",
                "장갑",
                "장갑",
                "캡 모자",
                "캡 모자",
                "캡 모자",
            ],
        },
    },
    {
        temperature:4,
        clothes:{
            outer: [
                "url('./images/clothes/~4/outer/두꺼운 코트1.png')",
                "url('./images/clothes/~4/outer/두꺼운 코트2.png')",
                "url('./images/clothes/~4/outer/롱패딩.png')",
                "url('./images/clothes/~4/outer/무스탕.png')",
                "url('./images/clothes/~4/outer/숏패딩1.png')",
                "url('./images/clothes/~4/outer/숏패딩2.png')",
                "url('./images/clothes/~4/outer/헤비 아우터.png')",
            ],
            top: [
                "url('./images/clothes/~4/top/니트.png')",
                "url('./images/clothes/~4/top/니트2.png')",
                "url('./images/clothes/~4/top/니트3.png')",
                "url('./images/clothes/~4/top/맨투맨.png')",
                "url('./images/clothes/~4/top/목폴라.png')",
                "url('./images/clothes/~4/top/후드티1.png')",
                "url('./images/clothes/~4/top/후드티2.png')",
            ],
            pants: [
                "url('./images/clothes/~4/pants/면 바지.png')",
                "url('./images/clothes/~4/pants/슬랙스1.png')",
                "url('./images/clothes/~4/pants/슬랙스2.png')",
                "url('./images/clothes/~4/pants/청바지.png')",
                "url('./images/clothes/~4/pants/카고 바지.png')",
                "url('./images/clothes/~4/pants/트레이닝 팬츠.png')",
            ],
            socks: [
                "url('./images/clothes/~4/socks/socks1.png')",
                "url('./images/clothes/~4/socks/socks2.png')",
                "url('./images/clothes/~4/socks/socks3.png')",
                "url('./images/clothes/~4/socks/socks4.png')",
                "url('./images/clothes/~4/socks/socks5.png')",
                "url('./images/clothes/~4/socks/socks6.png')",
            ],
            acc: [
                "url('./images/clothes/~4/acc/귀도리.png')",
                "url('./images/clothes/~4/acc/목도리.png')",
                "url('./images/clothes/~4/acc/목도리2.png')",
                "url('./images/clothes/~4/acc/비니.png')",
                "url('./images/clothes/~4/acc/비니2.png')",
                "url('./images/clothes/~4/acc/장갑.png')",
                "url('./images/clothes/~4/acc/장갑2.png')",
                "url('./images/clothes/~4/acc/캡 모자.png')",
                "url('./images/clothes/~4/acc/캡 모자2.png')",
                "url('./images/clothes/~4/acc/캡 모자3.png')",
            ]
        },
        clothesName:{
            outer: [
                "두꺼운 코트",
                "두꺼운 코트",
                "롱패딩",
                "무스탕",
                "숏패딩",
                "숏패딩",
                "헤비 아우터",
            ],
            top: [
                "니트",
                "니트",
                "니트",
                "맨투맨",
                "목폴라",
                "후드티",
                "후드티",
            ],
            pants: [
                "면 바지",
                "슬랙스",
                "슬랙스",
                "청바지",
                "카고 바지",
                "트레이닝 팬츠",
            ],
            socks: [
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
                "양말",
            ],
            acc: [
                "귀도리",
                "목도리",
                "목도리",
                "비니",
                "비니",
                "장갑",
                "장갑",
                "캡 모자",
                "캡 모자",
                "캡 모자",
            ],
        },
    },
];
